### PR TITLE
fixed Swagger error 500

### PR DESCRIPTION
**Pull request by gregorybleiker**
I was getting errors when trying to use swagger with this project. It was related to the BaseController. It was supplying a "Render" method to the controllers without a Http attribute. Furthermore, AuthorizationController did not have a Route attribute, so that both BaseController and AuthorizationController would have had an identical route to "Render".
I somewhat randomly fixed this by giving these some names, "index" and "connect/[controller]"

### CODE REVIEW

**Comment by asadsahi** [comment]
@gregorybleiker thanks. You spotted it well. However, I have fixed it in a [separate branch](https://github.com/asadsahi/AspNetCoreSpa/blob/ssr/Server/Helpers/Helpers.cs#L23) using a different mechanism. Just moved render in a different class rather in BaseController. Not sure amending connent/authorize is a good idea as it is used in few different flows. However moving render outside BaseController will require less number of changes.

Do you wanna give a shot and make similar changes in master?

**Comment by gregorybleiker** [comment]
If you have fixed it, just push it to the master branch, no? I think it makes for a bad experience when you clone the repo and things don't work. Factoring the method out is a good solution as well, I think.

**Comment by gregorybleiker** [comment]
If you have fixed it, why don't you push it to the master branch? I think it makes for a bad experience if you clone a repo and things don't work. Factoring out the method is a good solution.

**Comment by asadsahi** [comment]
@gregorybleiker [this](https://github.com/asadsahi/AspNetCoreSpa/commit/505e47a6a3145802d15c46ab70a6a84fee3afc1c) should fix it. Just wanted you to take the lead on this fix. :)

Anyway thanks for pointing out.

**Pull request closed without merging**
